neptunecontrib/monitoring/reporting.py
* added plot_binary_classification which was omitted by mistake
=> added binary clf plot

docs/conf.py, docs/index.rst
=> mocked missing imports

neptunecontrib/monitoring/skopt.py
* fixed qualified_project_name -> project_qualified_name
=> fixed qualified_project_name typo

neptunecontrib/hpo/utils.py
* fixed df2results best score/params
=> fixed df2results

neptunecontrib/api/utils.py, neptunecontrib/versioning/__init__.py, neptunecontrib/versioning/data.py
* added data versioning for file and directory
* added helper to get all files from dir and subdir with given extensions to pass it to `neptune.create_experiments(upload_source_files=get_filepaths())`
=> Data and file versions

neptunecontrib/versioning/data.py, requirements.txt
* added data versioning for s3 buckets
=> Version s3

docs/conf.py, neptunecontrib/monitoring/utils.py, setup.py
* added helper for logging matplotlib figures
=> added helper for logging matplotlib figures

docs/conf.py, neptunecontrib/monitoring/utils.py, requirements.txt, setup.py
* added helper for pickling object before sending artifact
=> added send artifact helper

docs/conf.py, docs/examples/examples_index.rst, docs/examples/image_dir_snapshots.ipynb, neptunecontrib/versioning/data.py, setup.py
* added visual snapshotting of image folders
* added example with gifs
=> Image data snapshots

docs/conf.py, neptunecontrib/versioning/data.py, setup.py
* fixed image dir snapshot mosaic plotting
=> fixed mosaic plotting

docs/conf.py, neptunecontrib/monitoring/metrics.py, neptunecontrib/versioning/data.py, setup.py
* added prefix to binary metrics logging
=> added prefix to binary metrics logging

docs/conf.py, neptunecontrib/monitoring/metrics.py, setup.py
* fixed threshold charts for false rates
=>  fixed threshold charts for false rates

docs/conf.py, neptunecontrib/monitoring/metrics.py, setup.py
* added labels to threshold charts
* added labels to the confusion matrix
=> Added labels to charts

docs/conf.py, neptunecontrib/monitoring/fairness.py, setup.py
* changed sensitive -> senstive_attributes
* fixed example in docstrings
=> fixed naming and docstrings

docs/conf.py, docs/examples/observer_sacred.ipynb, neptunecontrib/monitoring/sacred.py, setup.py
* updated docstrings
* updated examples with new go-to experiment
=> updated go-to experiment

docs/conf.py, neptunecontrib/monitoring/fastai.py, pylintrc, setup.py
* updated setup to show long description and support contact
* small naming fix in fastai callback
=> updated status with description, fixed naming in fastai

docs/conf.py, neptunecontrib/monitoring/skopt.py, setup.py
* added log_results
* added best_so_far_run_score channel
* renamed send_ -> log_
=> updated skopt logging added log_results

neptunecontrib/api/chart.py
Fixed:
* changed `neptunecontrib.logging.chart` -> `neptunecontrib.api` in the docstrings
=> fixed imports in the docstrings

neptunecontrib/monitoring/optuna.py
New:
* added logging of interactive visualizations from optuna via `log_chart` both after the training and after every iteration
* added logging of study object after every iteration
Changed:
*  renamed `NeptuneMonitor` to `NeptuneCallback` for consistency
=> Optuna NeptuneMonitor upgrades

neptunecontrib/monitoring/keras.py
A first attempt at providing Keras callbacks.
Please see comment for issues where input is needed
=> Adds Keras callback support

neptunecontrib/api/explainers.py
Added:
* `numerical_features` argument to `log_global_explanations` to choose the numerical variables that should be plotted explicitly
=> fixed the plotting for numerical variables in global explanations

docs/index.rst, docs/user_guide/create_experiment_comparison_comment, docs/user_guide/create_experiment_from_json, neptunecontrib/create_experiment_comparison_comment.py, neptunecontrib/create_experiment_comparison_markdown_table.py, neptunecontrib/create_experiment_from_json.py, neptunecontrib/sync/with_json.py
Added:
* helper script that creates a markdown file with a comparison table that shows a diff between to experiments
* auto-generated docs
Changed:
* moved `neptunecontrib.sync.with_json` to main `neptunecontrib` module for simplicity and consistency
=> added a helper script that creates comparison markdown table

neptunecontrib/bla.py, neptunecontrib/create_experiment_comparison_comment.py
* fixed link to experiment comparison
* fixed parsing of non-float values in metrics (text channels are treated as channel_ in our current api)
=> Fixed github action helper

neptunecontrib/monitoring/optuna.py
* added options to turn on/off logging particular charts
* dropped deprecated NeptuneMonitor and log_study
=> Added options to turn on/off logging of charts
